import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const asah = localFont({ src: "../public/font/Asah.ttf", variable: "--font-asah", display: "swap" });
const urbanist = localFont({ src: "../public/font/urbanist.ttf", variable: "--font-urbanist", display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${asah.variable} ${urbanist.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
